#!/bin/bash

mpicc hello-mm.c -o hello-mm

python3 killmpirun.py
cat /etc/hosts | grep 172 | grep -v controller | awk '{print $1}' | \
    while read host;
        do echo "rsync -avz --progress /root/mcmpi-hpc/ $host:/root/mcmpi-hpc"; done \
        | sh -x

sleep 5

./mcmpirun hello-mm
