#!/bin/bash

app_path=$1

export OMPI_ALLOW_RUN_AS_ROOT=1
export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

sed -i "/.*worker[0-9][2-9]/d" /etc/hosts
echo 0 > aws-dummy
./resetspawn.sh

echo "1-1" > container-idx

[ -f server.uri ] && rm -f ./server.uri
ps aux | grep ompi-server | awk '{print "kill -9 " $2}' | bash -x || true


screen -wipe || true
screen -x ompi-server -X quit || true
screen -dmS ompi-server bash -c "ompi-server --no-daemonize -r ./server.uri"
sleep 3

export MCMPI_MASTER=1
export MCMPI_SERVER_URI=$(cat ./server.uri)
echo ">> $MCMPI_SERVER_URI"

export MCMPI_HOSTFILE="$PWD/mcmpi_hostfile"
rm -f hello preload.so *nodetable *buffers output *dat
rm -f app-elastic

# COMPILAR PRELOAD.SO
##
##
##
mpicc -shared -fPIC -I./ preload.c -o preload.so -ldl -lpthread


# COMPILAR APP-ELASTIC
##
##
##
mpicc app-elastic.c -I./ preload.so -o app-elastic -lpthread -lm

# RUN
##
##
##

export MCMPI_HOSTFILE="$PWD/mcmpi_hostfile"
export MCMPI_MASTER=1
#mcmpirun ./app
#apppath=$1
    #-x APP_PATH=$1 \
    #-x LD_PRELOAD=`pwd`/preload.so \
LD_PRELOAD=`pwd`/preload.so \
mpirun -n 1 \
    -x APP_PATH=$app_path \
    -x MCMPI_APP=1 \
    -host client:1,localhost:1 \
    --oversubscribe \
    --allow-run-as-root \
    --ompi-server file:./server.uri \
    ./app-elastic 2>&1 | tee output.txt

